### PR TITLE
fix latin tagset

### PR DESCRIPTION
**Pull request by TDBuck**
Changed the placeholder letter for supine to z instead of s in the lat_attribute.json file.  Let me know if there are any other changes I need to make to fix issue #47

### CODE REVIEW

**Comment by balmas** [comment]
@TDBuck can you redo the pull request so that it contains only the change to the lat_attributes.json?
Thanks!

**Comment by PonteIneptique** [comment]
@TDBuck is like
This

**Comment by balmas** [comment]
sorry :(  also, just checking, did @gcelano confirm that 'z' is the right code to use? I can't find any info about this myself..

**Comment by TDBuck** [comment]
@balmas  I couldn't either, but I assumed it would work since it's a unique letter. 

@PonteIneptique  too real man, too real. 

I can go back and redo.

**Pull request closed without merging**
